---
- x: 0
  y: 0
  col: stone
- x: 1
  y: 0
  col: stone
- x: 2
  y: 0
  col: stone
- x: 4
  y: 0
  col: stone
- x: 11
  y: 2
  col: brick
- x: 12
  y: 2
  col: brick
- x: 13
  y: 2
  col: brick
- x: 14
  y: 2
  col: brick
- x: 15
  y: 2
  col: brick
- x: 16
  y: 2
  col: brick
- x: 19
  y: 2
  col: stone
- x: 0
  y: 14
  col: stone
- x: 19
  y: 14
  col: stone
- x: 6
  y: 0
  col: stone
- x: 7
  y: 0
  col: stone
- x: 9
  y: 0
  col: stone
- x: 11
  y: 0
  col: stone
- x: 14
  y: 0
  col: stone
- x: 16
  y: 0
  col: stone
- x: 17
  y: 0
  col: stone
- x: 19
  y: 0
  col: stone
- x: 12
  y: 0
  col: stone
- x: 0
  y: 12
  col: stone
- x: 0
  y: 10
  col: stone
- x: 0
  y: 9
  col: stone
- x: 0
  y: 5
  col: stone
- x: 0
  y: 4
  col: stone
- x: 0
  y: 2
  col: stone
- x: 3
  y: 5
  col: stone
- x: 2
  y: 6
  col: stone
- x: 1
  y: 7
  col: stone
- x: 16
  y: 6
  col: stone
- x: 15
  y: 6
  col: stone
- x: 18
  y: 14
  col: stone
- x: 16
  y: 14
  col: stone
- x: 15
  y: 14
  col: stone
- x: 13
  y: 14
  col: stone
- x: 10
  y: 14
  col: stone
- x: 8
  y: 14
  col: stone
- x: 6
  y: 14
  col: stone
- x: 5
  y: 14
  col: stone
- x: 3
  y: 14
  col: stone
- x: 19
  y: 13
  col: stone
- x: 19
  y: 12
  col: stone
- x: 19
  y: 8
  col: stone
- x: 19
  y: 7
  col: stone
- x: 19
  y: 5
  col: stone
- x: 19
  y: 3
  col: stone
- x: 1
  y: 14
  col: stone
- x: 7
  y: 4
  col: wood
- x: 9
  y: 4
  col: wood
- x: 6
  y: 5
  col: wood
- x: 10
  y: 5
  col: wood
- x: 6
  y: 7
  col: wood
- x: 7
  y: 8
  col: wood
- x: 10
  y: 7
  col: wood
- x: 9
  y: 8
  col: wood
- x: 0
  y: 6
  col: stone
- x: 0
  y: 3
  col: stone
- x: 0
  y: 1
  col: stone
- x: 3
  y: 0
  col: stone
- x: 5
  y: 0
  col: stone
- x: 8
  y: 0
  col: stone
- x: 10
  y: 0
  col: stone
- x: 13
  y: 0
  col: stone
- x: 15
  y: 0
  col: stone
- x: 18
  y: 0
  col: stone
- x: 19
  y: 1
  col: stone
- x: 19
  y: 4
  col: stone
- x: 19
  y: 6
  col: stone
- x: 19
  y: 9
  col: stone
- x: 19
  y: 10
  col: stone
- x: 19
  y: 11
  col: stone
- x: 2
  y: 14
  col: stone
- x: 4
  y: 14
  col: stone
- x: 7
  y: 14
  col: stone
- x: 9
  y: 14
  col: stone
- x: 11
  y: 14
  col: stone
- x: 14
  y: 14
  col: stone
- x: 17
  y: 14
  col: stone
- x: 0
  y: 8
  col: stone
- x: 0
  y: 7
  col: stone
- x: 0
  y: 11
  col: stone
- x: 0
  y: 13
  col: stone
- x: 4
  y: 9
  col: brick
- x: 4
  y: 11
  col: brick
- x: 4
  y: 10
  col: brick
- x: 5
  y: 9
  col: brick
- x: 12
  y: 10
  col: wood
- x: 13
  y: 10
  col: wood
- x: 14
  y: 10
  col: wood
- x: 15
  y: 10
  col: wood
- x: 12
  y: 14
  col: stone
